// <auto-generated />
using System;
using System.Collections.Generic;
namespace JetBrains.Annotations
{
    public class UsedImplicitlyAttribute
    {
    }
}

namespace RimWorld
{
    public class Beam
    {
    }
    public class Bombardment
    {
    }
    public class BombardmentProjectile
    {
    }
    public class Building_Door
    {
        public bool PawnCanOpen(Verse.Pawn p) => default;
        public void StartManualOpenBy(Verse.Pawn opener) {{ }}
    }
    public class Building_Storage
    {
    }
    public class Building_TurretGun
    {
    }
    public class BuildingProperties
    {
    }
    public class Faction
    {
    }
    public class ForbidUtility
    {
        public static bool IsForbidden(Verse.IntVec3 c, Verse.Pawn pawn) => default;
    }
    public interface ITrader
    {
        public System.Collections.Generic.IEnumerable<Verse.Thing> ColonyThingsWillingToBuy(Verse.Pawn playerNegotiator) => default;
    }
    public class KeyBindingDefOf
    {
    }
    public class Skyfaller
    {
    }
    public class StoreUtility
    {
    }
    public class TraderKindDef
    {
    }
    public class WorkGiver_Scanner
    {
    }
}

namespace RimWorld.Planet
{
    public struct GlobalTargetInfo
    {
    }
    public class PocketMapParent
    {
    }
}

namespace UnityEngine
{
    public struct Color
    {
    }
    public class Material
    {
    }
    public struct Matrix4x4
    {
    }
    public struct Quaternion
    {
    }
    public class Texture2D
    {
    }
    public class Time
    {
    }
    public struct Vector3
    {
        public static float Distance(UnityEngine.Vector3 a, UnityEngine.Vector3 b) => default;
        public static float Dot(UnityEngine.Vector3 lhs, UnityEngine.Vector3 rhs) => default;
    }
}

namespace Verse
{
    public struct AcceptanceReport
    {
    }
    public enum AltitudeLayer { None }
    public class Altitudes
    {
        public static float AltitudeFor(Verse.AltitudeLayer alt) => default;
    }
    public class BuildableDef
    {
    }
    public class Building
    {
    }
    public struct CellRect
    {
        public static Verse.CellRect WholeMap(Verse.Map map) => default;
    }
    public class CellRenderer
    {
    }
    public class ColorExtension
    {
        public static UnityEngine.Color ToTransparent(UnityEngine.Color c, float transparency) => default;
    }
    public class ColorLibrary
    {
    }
    public class CompProperties
    {
    }
    public enum Danger { None }
    public class DebugMatsSpectrum
    {
        public static UnityEngine.Material Mat(int ind, bool transparent) => default;
    }
    public class Def
    {
    }
    public class Designator
    {
    }
    public class Find
    {
    }
    public class GenClosest
    {
    }
    public class GenCollection
    {
        public static int Replace(System.Collections.Generic.IList<T> list, T replace, T with) => default;
        public static System.Collections.Generic.IEnumerable<T> Concat(System.Collections.Generic.IEnumerable<T> lhs, T rhs) => default;
    }
    public class GenDraw
    {
        public static void DrawRadiusRing(Verse.IntVec3 center, float radius) {{ }}
    }
    public class GenGrid
    {
        public static bool InBounds(Verse.IntVec3 c, Verse.Map map) => default;
    }
    public class GenRadial
    {
        public static System.Collections.Generic.IEnumerable<Verse.IntVec3> RadialCellsAround(Verse.IntVec3 center, float minRadius, float maxRadius) => default;
    }
    public class GenSpawn
    {
    }
    public class GenTypes
    {
        public static System.Type GetTypeInAnyAssembly(string typeName, string namespaceIfAmbiguous) => default;
        public static System.Collections.Generic.List<System.Type> AllSubclasses(System.Type baseType) => default;
        public static bool SameOrSubclassOf(System.Type baseType, System.Type parentType) => default;
        public static System.Collections.Generic.List<System.Type> AllSubclassesNonAbstract(System.Type baseType) => default;
    }
    public class GridsUtility
    {
        public static Verse.Room GetRoom(Verse.IntVec3 loc, Verse.Map map) => default;
        public static System.Collections.Generic.List<Verse.Thing> GetThingList(Verse.IntVec3 c, Verse.Map map) => default;
        public static Verse.Building GetEdifice(Verse.IntVec3 c, Verse.Map map) => default;
    }
    public interface ILoadReferenceable
    {
    }
    public struct IntVec3
    {
        public UnityEngine.Vector3 ToVector3Shifted() => default;
        public UnityEngine.Vector3 ToVector3ShiftedWithAltitude(float AddedAltitude) => default;
    }
    public class IntVec3Utility
    {
        public static Verse.IntVec3 ToIntVec3(UnityEngine.Vector3 vect) => default;
    }
    public class JobDef
    {
    }
    public class JobMaker
    {
    }
    public class KeyBindingDef
    {
    }
    public class ListerBuildings
    {
    }
    public class ListerThings
    {
    }
    public enum LoadSaveMode { None }
    public struct LocalTargetInfo
    {
    }
    public class Map
    {
        public Verse.MapComponent GetComponent(System.Type type) => default;
    }
    public class MapComponent
    {
    }
    public class ModsConfig
    {
        public static bool IsActive(string id) => default;
    }
    public class Pawn
    {
    }
    public class Pawn_DrawTracker
    {
    }
    public class PawnTweener
    {
    }
    public class Projectile
    {
    }
    public class ReachabilityImmediate
    {
    }
    public class Room
    {
    }
    public struct Rot4
    {
    }
    public class Scribe
    {
    }
    public class ShootLeanUtility
    {
    }
    public class StaticConstructorOnStartup
    {
    }
    public struct TargetInfo
    {
    }
    public class Thing
    {
    }
    public class ThingComp
    {
    }
    public class ThingCompUtility
    {
        public static T TryGetComp(Verse.Thing thing) => default;
        public static bool TryGetComp(Verse.Thing thing, out T comp) => default;
    }
    public class ThingDef
    {
    }
    public class ThingUtility
    {
        public static bool DestroyedOrNull(Verse.Thing t) => default;
    }
    public class ThingWithComps
    {
    }
    public enum TraverseMode { None }
    public struct TraverseParms
    {
    }
    public class UI
    {
        public static UnityEngine.Vector3 MouseMapPosition() => default;
    }
    public class Verb
    {
    }
    public class Verb_ShootBeam
    {
    }
    public class VerbProperties
    {
    }
    public enum WipeMode { None }
}

namespace Verse.AI
{
    public interface IAttackTarget
    {
    }
    public interface IAttackTargetSearcher
    {
    }
    public class Job
    {
        public Verse.AI.Job Clone() => default;
        public Verse.LocalTargetInfo GetTarget(Verse.AI.TargetIndex ind) => default;
    }
    public class JobDriver
    {
    }
    public struct JobIssueParams
    {
    }
    public enum JobTag { None }
    public enum LocomotionUrgency { None }
    public enum PathEndMode { None }
    public class ReservationUtility
    {
        public static void ReserveAsManyAsPossible(Verse.Pawn p, System.Collections.Generic.List<Verse.LocalTargetInfo> target, Verse.AI.Job job, int maxPawns, int stackCount, Verse.ReservationLayerDef layer) {{ }}
        public static bool Reserve(Verse.Pawn p, Verse.LocalTargetInfo target, Verse.AI.Job job, int maxPawns, int stackCount, Verse.ReservationLayerDef layer, bool errorOnFailed, bool ignoreOtherReservations) => default;
    }
    public enum TargetIndex { None }
    public enum TargetScanFlags { None }
    public class ThinkNode
    {
    }
    public class ThinkNode_JobGiver
    {
        public Verse.AI.ThinkResult TryIssueJobPackage(Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) => default;
    }
    public struct ThinkResult
    {
    }
    public class Toil
    {
    }
}

