#:package Microsoft.CodeAnalysis.CSharp@5.3.0

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

const string ProjectRoot = "../VehicleMapFramework";
const string AssemblyFolderPath = "../../../../RimWorldWin64_Data/Managed";
const string OutputFilePath = "./Stubs.cs";

var files = Directory.GetFiles(Path.Combine(ProjectRoot, "VMF_HarmonyPatches/ModCompat"), "*.cs")
    .Append(Path.Combine(ProjectRoot, "ModCompat.cs"))
    .Where(File.Exists)
    .ToList();

var syntaxTrees = files.Select(f => CSharpSyntaxTree.ParseText(File.ReadAllText(f))).ToList();
var assemblies = Directory.GetFiles(AssemblyFolderPath, "*.dll");
var assemblyNames = assemblies.Select(Path.GetFileNameWithoutExtension).ToHashSet();

var trustedAssemblies = ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!).Split(Path.PathSeparator);
var baseReferences = trustedAssemblies
    .Select(path => MetadataReference.CreateFromFile(path))
    .ToList();

var systemDllNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
{
    "mscorlib", "System", "System.Core", "System.Runtime", "System.Collections", 
    "System.Private.CoreLib", "netstandard", "System.Drawing", "System.Xml", "System.Numerics"
};

var gameDlls = Directory.GetFiles(AssemblyFolderPath, "*.dll")
    .Where(path => !systemDllNames.Contains(Path.GetFileNameWithoutExtension(path))) // システム系を除外
    .Select(path => MetadataReference.CreateFromFile(path))
    .ToList();

var compilation = CSharpCompilation.Create("StubAnalysis")
    .AddReferences(baseReferences) // 標準ライブラリ
    .AddReferences(gameDlls)       // RW + Unity
    .AddSyntaxTrees(syntaxTrees);

var foundTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
var methodSignatures = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);

foreach (var tree in syntaxTrees)
{
    var model = compilation.GetSemanticModel(tree);
    var root = tree.GetRoot();

    var allTypes = root.DescendantNodes().OfType<TypeSyntax>();
    foreach (var typeSyntax in allTypes)
    {
        var typeSymbol = model.GetTypeInfo(typeSyntax).Type;
        AddRimWorldTypesRecursively(typeSymbol, foundTypes);
    }

    var invocations = root.DescendantNodes().OfType<InvocationExpressionSyntax>();
    foreach (var invocation in invocations)
    {
        var symbolInfo = model.GetSymbolInfo(invocation);
        if (symbolInfo.Symbol is IMethodSymbol { ContainingAssembly: { } assembly } methodSymbol &&
            assemblyNames.Contains(assembly.Name))
        {
            methodSignatures.Add(methodSymbol);
            AddRimWorldTypesRecursively(methodSymbol.ContainingType, foundTypes);
        }
    }
}

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("using System;");
sb.AppendLine("using System.Collections.Generic;");

var groupedTypes = foundTypes
    .OrderBy(t => t.ToDisplayString())
    .GroupBy(t => t.ContainingNamespace?.ToDisplayString() ?? "Global");

foreach (var nsGroup in groupedTypes)
{
    sb.AppendLine($"namespace {nsGroup.Key}");
    sb.AppendLine("{");
    foreach (var type in nsGroup)
    {
        var kind = type.TypeKind switch
        {
            TypeKind.Interface => "interface",
            TypeKind.Struct => "struct",
            TypeKind.Enum => "enum",
            _ when type.IsValueType => "struct",
            _ => "class"
        };

        var isEnum = type.TypeKind == TypeKind.Enum;
        if (isEnum)
        {
            // Enum の場合は中身が空だとエラーになることがあるので最小限の値を定義
            sb.AppendLine($"    public enum {type.Name} {{ None }}");
        }
        else
        {
            sb.AppendLine($"    public {kind} {type.Name}");
            sb.AppendLine("    {");
        }
        
        var methods = methodSignatures.Where(m => SymbolEqualityComparer.Default.Equals(m.ContainingType, type));
        foreach (var m in methods)
        {
            var m2 = m.ReducedFrom ?? m;
            var staticModifier = m2.IsStatic ? "static " : "";
            var returnType = m2.ReturnType.ToDisplayString();
            var paramList = new List<string>();
            for (int i = 0; i < m2.Parameters.Length; i++)
            {
                var p = m2.Parameters[i];
                var modifier = p.RefKind switch {
                    RefKind.Ref => "ref ",
                    RefKind.Out => "out ",
                    RefKind.In => "in ",
                    _ => ""
                };
                var isParams = p.IsParams ? "params " : "";
                paramList.Add($"{modifier}{isParams}{p.Type.ToDisplayString()} {p.Name}");
            }
            var parameters = string.Join(", ", paramList);
            var result = m2.ReturnsVoid ? "{{ }}" : "=> default;";
            sb.AppendLine($"        public {staticModifier}{returnType} {m.Name}({parameters}) {result}");
        }

        if (!isEnum) sb.AppendLine("    }");
    }
    sb.AppendLine("}");
    sb.AppendLine();
}

File.WriteAllText(OutputFilePath, sb.ToString(), Encoding.UTF8);
Console.WriteLine($"Generated {foundTypes.Count} types to {OutputFilePath}");
return;

void AddRimWorldTypesRecursively(ITypeSymbol? symbol, HashSet<ITypeSymbol> results)
{
    while (true)
    {
        if (symbol == null || symbol.TypeKind == TypeKind.TypeParameter || symbol.TypeKind == TypeKind.Delegate) return;

        if (symbol is IArrayTypeSymbol arrayType)
        {
            symbol = arrayType.ElementType;
            continue;
        }

        var asmName = symbol.ContainingAssembly?.Name;
        if (asmName != null && assemblyNames.Contains(asmName) && !asmName.StartsWith("System"))
        {
            var targetSymbol = symbol is INamedTypeSymbol { IsGenericType: true } named
                ? named.ConstructedFrom
                : symbol;

            results.Add(targetSymbol);
        }

        if (symbol is INamedTypeSymbol { IsGenericType: true } namedSymbol)
        {
            foreach (var arg in namedSymbol.TypeArguments) AddRimWorldTypesRecursively(arg, results);
        }
        break;
    }
}