<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  <TargetFramework>net48</TargetFramework>
  <OutputType>Library</OutputType>
  <RootNamespace>VehicleMapFramework</RootNamespace>
  <AssemblyName>VehicleMapFramework</AssemblyName>
  <LangVersion>preview</LangVersion>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<ImplicitUsings>disable</ImplicitUsings>
	<Configurations>Debug;Release;Dev</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\1.6\Assemblies\</OutputPath>
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\..\1.6\Assemblies\</OutputPath>
    <Optimize>True</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
    <DebugType>none</DebugType>
    <OutputPath>..\..\..\VehicleMapFrameworkDev\1.6\Assemblies\</OutputPath>
    <Optimize>True</Optimize>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" />
    <PackageReference Include="Lib.Harmony.Ref" />
	<PackageReference Include="Nerdbank.GitVersioning">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>
  
  <PropertyGroup>
    <SteamWorkshopRoot Condition="'$(SteamWorkshopRoot)' == ''">..\..\..\..\..\..\workshop\content\294100</SteamWorkshopRoot>
  </PropertyGroup>
  <PropertyGroup>
		<VFUnstableFolder Condition="'$(CIBuild)' == 'true'">$(SteamWorkshopRoot)\3522907382</VFUnstableFolder>
    <VFUnstableFolder Condition="'$(CIBuild)' != 'true'">..\..\..\VehicleFramework</VFUnstableFolder>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)'=='Dev'">
    <Reference Include="SmashTools">
      <HintPath>$(VFUnstableFolder)\1.6\Assemblies\SmashTools.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Vehicles">
      <HintPath>$(VFUnstableFolder)\1.6\Assemblies\Vehicles.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)'=='Release'or'$(Configuration)'=='Debug'">
    <Reference Include="SmashTools">
      <HintPath>$(SteamWorkshopRoot)\3014915404\1.6\Assemblies\SmashTools.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Vehicles">
      <HintPath>$(SteamWorkshopRoot)\3014915404\1.6\Assemblies\Vehicles.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Drawing">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.IO.Compression.FileSystem">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
    <Reference Update="System.Numerics">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Runtime.Serialization">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\.github\workflows\build.yml">
      <Link>build.yml</Link>
    </Content>
    <Content Include="..\..\.git\hooks\pre-push">
      <Link>pre-push</Link>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <AboutFolderPath Condition="'$(AboutXmlPath)' == ''">../../About</AboutFolderPath>
    <AboutFolderPath Condition="'$(Configuration)'=='Dev'">../../Dev/About</AboutFolderPath>
  </PropertyGroup>
  <Target Name="UpdateVersion" AfterTargets="PostBuildEvent" Condition="'$(SkipPostBuild)' != 'true'">
    <Exec Command="powershell.exe -ExecutionPolicy Bypass -File &quot;$(ProjectDir)UpdateAboutXmlVersion.ps1&quot; -AboutXmlPath &quot;$(AboutFolderPath)/About.xml&quot; -BuiltDllPath &quot;$(TargetPath)&quot;" />
  </Target>
	<Target Name="CopyToDev" AfterTargets="PostBuildEvent" Condition="'$(Configuration)'=='Dev'">
		<Exec Command="(robocopy ../../1.5 ../../../VehicleMapFrameworkDev/1.5 /MIR /E /XD Assemblies) ^&amp; IF %ERRORLEVEL% LEQ 1 exit 0" />
		<Exec Command="(robocopy ../../1.6 ../../../VehicleMapFrameworkDev/1.6 /MIR /E /XD Assemblies) ^&amp; IF %ERRORLEVEL% LEQ 1 exit 0" />
		<Exec Command="(robocopy ../../Common ../../../VehicleMapFrameworkDev/Common /MIR /E /XD AssetBundles) ^&amp; IF %ERRORLEVEL% LEQ 1 exit 0" />
    <Exec Command="(robocopy ../../Dev/About ../../../VehicleMapFrameworkDev/About /MIR /E) ^&amp; IF %ERRORLEVEL% LEQ 1 exit 0" />
    <Exec Command="(robocopy ../../Dev/AssetBundles ../../../VehicleMapFrameworkDev/Common/AssetBundles /MIR /E) ^&amp; IF %ERRORLEVEL% LEQ 1 exit 0" />
    <Exec Command="(robocopy ../../Dev/ ../../../VehicleMapFrameworkDev LoadFolders.xml) ^&amp; IF %ERRORLEVEL% LEQ 1 exit 0" />
		<Exec Command="(robocopy ../../ ../../../VehicleMapFrameworkDev LICENSE) ^&amp; IF %ERRORLEVEL% LEQ 1 exit 0" />
	</Target>
</Project>