<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>VehicleMapFramework</RootNamespace>
    <LangVersion>preview</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Configurations>Debug;Release;Dev</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <OutputPath>..\..\1.6\_DubsBadHygiene\Assemblies\</OutputPath>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\..\1.6\_DubsBadHygiene\Assemblies\</OutputPath>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
    <DebugType>none</DebugType>
    <OutputPath>..\..\..\VehicleMapFrameworkDev\1.6\_DubsBadHygiene\Assemblies\</OutputPath>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
  </PropertyGroup>

  <PropertyGroup>
    <SteamWorkshopRoot Condition="'$(SteamWorkshopRoot)' == ''">..\..\..\..\..\..\workshop\content\294100</SteamWorkshopRoot>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0DubCore">
      <HintPath>$(SteamWorkshopRoot)\836308268\1.6\Assemblies\0DubCore.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BadHygiene">
      <HintPath>$(SteamWorkshopRoot)\836308268\1.6\Assemblies\BadHygiene.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.4.2"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VehicleMapFramework\VehicleMapFramework.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Core">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Data">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Drawing">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.IO.Compression.FileSystem">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Numerics">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Runtime.Serialization">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Xml">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Xml.Linq">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>