name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "1.6"
      - bug-fix
      - development

jobs:
  report_local_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Results
        run: |
          curl -L -o ./TestResults.xml "https://gist.githubusercontent.com/oelsart/3bb8183cedc9869f566440ca1553c633/raw/TestResults.xml"

      - name: Upload local test results artifact
        uses: actions/upload-artifact@v7
        with:
          name: LocalTestResults
          path: |
            ./TestResults.xml
      
      - name: Test Report
        uses: dorny/test-reporter@v3
        with:
          artifact: LocalTestResults
          name: Local Tests
          path: '*.xml'
          reporter: java-junit
          fail-on-error: 'true'
          
  build:
    runs-on: ubuntu-latest
    
    env:
      Solution_Name: VehicleMapFramework
      WorkshopMods: |
        3014915404  # Vehicle Framework
        2023507013  # Vanilla Expanded Framework
        730936602   # Achtung!
        2890901044  # Combat Extended
        836308268   # Dubs Bad Hygiene
        1321849735  # Rimefeller

    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: true
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 9.0.x
      
    - name: Restore Cache
      id: cache-steam
      uses: actions/cache/restore@v6
      with:
        path: ~/Steam
        key: steamcmd-initial
        restore-keys: |
          steamcmd-
          
    - name: Install SteamCMD
      if: steps.cache-steam.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/Steam
        cd ~/Steam
        curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -

    - name: Download Workshop Mods
      run: |
        mkdir -p ~/Steam/steamapps/workshop/content/294100
        
        {
          echo "login anonymous"
          while IFS= read -r line; do
            mod_id=$(echo "$line" | sed 's/#.*//' | xargs)
            [[ -n "$mod_id" ]] && echo "workshop_download_item 294100 $mod_id validate"
          done <<< "${{ env.WorkshopMods }}"
          echo "quit"
        } > steam_script.txt
        
        ~/Steam/steamcmd.sh +runscript "$(pwd)/steam_script.txt"
        
        echo "CI_SteamCMD_WorkShop=$HOME/Steam/steamapps/workshop/content/294100" >> $GITHUB_ENV
        ls -la ~/Steam/steamapps/workshop/content/294100
    
    - name: Generate Content Hash
      run: |
        MODS_HASH=$(find ~/Steam/steamapps/workshop/content/294100 -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum | awk '{print $1}')
        echo "MODS_HASH=$MODS_HASH" >> $GITHUB_ENV

    - name: Save Cache
      uses: actions/cache/save@v6
      with:
        path: ~/Steam
        key: steamcmd-${{ env.MODS_HASH }}
        enableCrossOsArchive: true

    - name: Restore Dependencies
      run: |
        dotnet restore Source/VehicleMapFramework/VehicleMapFramework.csproj
        dotnet restore Source/VMF_AchtungPatch/VMF_AchtungPatch.csproj
        dotnet restore Source/VMF_CEPatch/VMF_CEPatch.csproj
        dotnet restore Source/VMF_DBHCompat/VMF_DBHCompat.csproj
        dotnet restore Source/VMF_RimefellerCompat/VMF_RimefellerCompat.csproj
        dotnet restore Source/VMF_VEFCompat/VMF_VEFCompat.csproj

    - name: Build DLL
      run: |
        dotnet build Source/VehicleMapFramework/VehicleMapFramework.csproj --configuration Release --no-restore /p:SteamWorkshopRoot=${{ env.CI_SteamCMD_WorkShop }} /p:SkipPostBuild=true
        dotnet build Source/VMF_AchtungPatch/VMF_AchtungPatch.csproj --configuration Release --no-restore /p:SteamWorkshopRoot=${{ env.CI_SteamCMD_WorkShop }} /p:SkipPostBuild=true
        dotnet build Source/VMF_CEPatch/VMF_CEPatch.csproj --configuration Release --no-restore /p:SteamWorkshopRoot=${{ env.CI_SteamCMD_WorkShop }} /p:SkipPostBuild=true
        dotnet build Source/VMF_DBHCompat/VMF_DBHCompat.csproj --configuration Release --no-restore /p:SteamWorkshopRoot=${{ env.CI_SteamCMD_WorkShop }} /p:SkipPostBuild=true
        dotnet build Source/VMF_RimefellerCompat/VMF_RimefellerCompat.csproj --configuration Release --no-restore /p:SteamWorkshopRoot=${{ env.CI_SteamCMD_WorkShop }} /p:SkipPostBuild=true
        dotnet build Source/VMF_VEFCompat/VMF_VEFCompat.csproj --configuration Release --no-restore /p:SteamWorkshopRoot=${{ env.CI_SteamCMD_WorkShop }} /p:SkipPostBuild=true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: VehicleMapFramework
        path: |
          1.5
          1.6
          About
          Common
          LICENSE
          LoadFolders.xml