name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "1.6"
      - bug-fix
      - development
      - test-result-checker-test

jobs:
  report_local_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download TRX file
        run: |
          curl -L -o ./LocalTestResults.trx "${{ steps.get_trx.outputs.download_url }}"
            - name: Download TRX
              run: |
                curl -L -o ./LocalTestResults.trx "https://gist.githubusercontent.com/oelsart/4743ba5e7e55987224cc6fb29459fa4e/raw/TestResults.trx"

      - name: Upload local test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: LocalTestResults
          path: ./LocalTestResults.trx
            
      - name: Test Report
        uses: dorny/test-reporter@v2
        with:
          artifact: LocalTestResults
          name: Harmony Patch Tests
          path: '*.trx'
          reporter: dotnet-trx
          fail-on-error: 'true'
          
  build:
    runs-on: ubuntu-latest
    needs: report_local_tests
    
    env:
      Solution_Name: VehicleMapFramework
      Project_Path: Source/VehicleMapFramework/VehicleMapFramework.sln 
      WorkshopMods: |
        3014915404  # Vehicle Framework
        2023507013  # Vanilla Expanded Framework
        730936602   # Achtung!
        2890901044  # Combat Extended
        836308268   # Dubs Bad Hygiene
        1321849735  # Rimefeller

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore Dependencies
      run: dotnet restore ${{ env.Project_Path }}
      
    - name: Cache SteamCMD
      id: cache-steam
      uses: actions/cache@v4
      with:
        path: ~/Steam
        key: ${{ runner.os }}-steamcmd-v1
        restore-keys: |
          ${{ runner.os }}-steamcmd-
          
    - name: Install SteamCMD
      if: steps.cache-steam.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/Steam
        cd ~/Steam
        curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -

    - name: Download Workshop Mods
      run: |
        mkdir -p ~/Steam/steamapps/workshop/content/294100
        
        STEAM_COMMANDS="+login anonymous"
        
        while IFS= read -r mod_id; do
          if [ -n "$mod_id" ]; then
            echo "Queueing Workshop Mod: $mod_id"
            STEAM_COMMANDS="${STEAM_COMMANDS} +workshop_download_item 294100 $mod_id validate"
          fi
        done <<< "${{ env.WorkshopMods }}"
        
        STEAM_COMMANDS="${STEAM_COMMANDS} +quit"
        ~/Steam/steamcmd.sh ${STEAM_COMMANDS}
        
        echo "CI_SteamCMD_WorkShop=$HOME/Steam/steamapps/workshop/content/294100" >> $GITHUB_ENV
        ls -la ~/Steam/steamapps/workshop/content/294100

    - name: Build Mod DLL
      run: dotnet build ${{ env.Project_Path }} --configuration Release --no-restore /p:SkipPostBuild=true /p:SteamWorkshopRoot=${{ env.CI_SteamCMD_WorkShop }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VehicleMapFramework
        path: |
          1.5
          1.6
          About
          Common
          LICENSE
          LoadFolders.xml
